#sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "0.12"
  - "iojs"

before_script: "npm install -g codeclimate-test-reporter"
script: "make test-travis"

notifications:
  slack: babeljs:5Wy4QX13KVkGy9CnU0rmvgeK
